# Generated by Django 2.0.3 on 2018-10-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameraid', models.CharField(max_length=30)),
                ('cameraip', models.CharField(max_length=30)),
                ('alarmtime', models.DateTimeField(auto_now_add=True)),
                ('alarmdata', models.CharField(max_length=50)),
            ],
        ),
    ]
