# Generated by Django 2.0.3 on 2018-10-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiyuan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameraid', models.CharField(max_length=30)),
                ('cameraip', models.CharField(max_length=30)),
                ('alarmtime', models.DateTimeField(auto_now_add=True)),
                ('alarmdata', models.IntegerField()),
            ],
        ),
    ]
